var SwordWorld;
(function (SwordWorld) {
    SwordWorld.BackgroundHuman = {
        name: "Human Backgrounds",
        2: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 8,
            body: 4,
            mind: 9,
            exp: 2000,
        },
        3: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 8,
            body: 4,
            mind: 9,
            exp: 2000,
        },
        4: {
            name: "Magician",
            startingClass: "Sorcerer or Conjurer",
            skill: 7,
            body: 4,
            mind: 10,
            exp: 2000,
        },
        5: {
            name: "Magician",
            startingClass: "Sorcerer or Conjurer",
            skill: 7,
            body: 4,
            mind: 10,
            exp: 2000,
        },
        6: {
            name: "Agile Warrior",
            startingClass: "Scout and Fencer",
            skill: 10,
            body: 7,
            mind: 4,
            exp: 2000,
        },
        7: {
            name: "Normal",
            startingClass: "None",
            skill: 7,
            body: 7,
            mind: 7,
            exp: 3000,
        },
        8: {
            name: "Mercenary",
            startingClass: "Fighter or Grappler",
            skill: 7,
            body: 10,
            mind: 4,
            exp: 2000,
        },
        9: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 4,
            body: 8,
            mind: 9,
            exp: 2000,
        },
        10: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 4,
            body: 8,
            mind: 9,
            exp: 2000,
        },
        11: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 6,
            body: 6,
            mind: 9,
            exp: 2000,
        },
        12: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 6,
            body: 6,
            mind: 9,
            exp: 2000,
        },
    };
    SwordWorld.BackgroundUpdatedHuman = {
        name: "Updated Human Backgrounds",
        2: {
            name: "Spy",
            startingClass: "Scout",
            skill: 10,
            body: 6,
            mind: 5,
            exp: 2500,
        },
        3: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 9,
            body: 7,
            mind: 5,
            exp: 2500,
        },
        4: {
            name: "Bodybuilder",
            startingClass: "Enhancer",
            skill: 8,
            body: 8,
            mind: 5,
            exp: 2500,
        },
        5: {
            name: "Magician",
            startingClass: "Sorcerer",
            skill: 6,
            body: 5,
            mind: 10,
            exp: 2000,
        },
        6: {
            name: "Brawler",
            startingClass: "Grappler",
            skill: 8,
            body: 9,
            mind: 4,
            exp: 2000,
        },
        7: {
            name: "Mercenary",
            startingClass: "Fighter",
            skill: 7,
            body: 10,
            mind: 4,
            exp: 2000,
        },
        8: {
            name: "Agile Warrior",
            startingClass: "Fencer",
            skill: 9,
            body: 8,
            mind: 4,
            exp: 2500,
        },
        9: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 5,
            body: 6,
            mind: 10,
            exp: 2000,
        },
        10: {
            name: "Scholar",
            startingClass: "Sage",
            skill: 5,
            body: 7,
            mind: 9,
            exp: 2500,
        },
        11: {
            name: "Herbalist",
            startingClass: "Ranger",
            skill: 9,
            body: 4,
            mind: 8,
            exp: 2500,
        },
        12: {
            name: "Minstrel",
            startingClass: "Bard",
            skill: 7,
            body: 5,
            mind: 9,
            exp: 2500,
        },
    };
    SwordWorld.BackgroundElf = {
        name: "Elf Backgrounds",
        2: {
            name: "Warrior",
            startingClass: "Fencer",
            skill: 12,
            body: 5,
            mind: 9,
            exp: 2500,
        },
        3: {
            name: "Warrior",
            startingClass: "Fencer",
            skill: 12,
            body: 5,
            mind: 9,
            exp: 2500,
        },
        4: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 13,
            body: 5,
            mind: 8,
            exp: 2500,
        },
        5: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 13,
            body: 5,
            mind: 8,
            exp: 2500,
        },
        6: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 10,
            body: 4,
            mind: 12,
            exp: 2000,
        },
        7: {
            name: "Magician",
            startingClass: "Sorcerer",
            skill: 10,
            body: 3,
            mind: 13,
            exp: 2000,
        },
        8: {
            name: "Manipulator",
            startingClass: "Conjurer",
            skill: 9,
            body: 4,
            mind: 13,
            exp: 2000,
        },
        9: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 9,
            body: 5,
            mind: 12,
            exp: 2000,
        },
        10: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 9,
            body: 5,
            mind: 12,
            exp: 2000,
        },
        11: {
            name: "Herbalist",
            startingClass: "Sage & Ranger",
            skill: 10,
            body: 5,
            mind: 11,
            exp: 2000,
        },
        12: {
            name: "Herbalist",
            startingClass: "Sage & Ranger",
            skill: 10,
            body: 5,
            mind: 11,
            exp: 2000,
        },
    };
    SwordWorld.BackgroundUpdatedElf = {
        name: "Updated Elf Backgrounds",
        2: {
            name: "Bodybuilder",
            startingClass: "Enhancer",
            skill: 11,
            body: 5,
            mind: 10,
            exp: 2500,
        },
        3: {
            name: "Bodybuilder",
            startingClass: "Enhancer",
            skill: 11,
            body: 5,
            mind: 10,
            exp: 2500,
        },
        4: {
            name: "Bodybuilder",
            startingClass: "Enhancer",
            skill: 11,
            body: 5,
            mind: 10,
            exp: 2500,
        },
        5: {
            name: "Hunter",
            startingClass: "Marksman & Ranger",
            skill: 12,
            body: 3,
            mind: 11,
            exp: 2000,
        },
        6: {
            name: "Hunter",
            startingClass: "Marksman & Ranger",
            skill: 12,
            body: 3,
            mind: 11,
            exp: 2000,
        },
        7: {
            name: "Magician",
            startingClass: "Sorcerer",
            skill: 10,
            body: 2,
            mind: 14,
            exp: 2000,
        },
        8: {
            name: "Soldier",
            startingClass: "Fighter or Grappler",
            skill: 12,
            body: 6,
            mind: 8,
            exp: 2000,
        },
        9: {
            name: "Soldier",
            startingClass: "Fighter or Grappler",
            skill: 12,
            body: 6,
            mind: 8,
            exp: 2000,
        },
        10: {
            name: "Minstrel",
            startingClass: "Ranger & Bard",
            skill: 11,
            body: 4,
            mind: 11,
            exp: 2000,
        },
        11: {
            name: "Minstrel",
            startingClass: "Ranger & Bard",
            skill: 11,
            body: 4,
            mind: 11,
            exp: 2000,
        },
        12: {
            name: "Minstrel",
            startingClass: "Ranger & Bard",
            skill: 11,
            body: 4,
            mind: 11,
            exp: 2000,
        },
    };
    SwordWorld.BackgroundDwarf = {
        name: "Dwarf Backgrounds",
        2: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 6,
            body: 8,
            mind: 6,
            exp: 2500,
        },
        3: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 6,
            body: 8,
            mind: 6,
            exp: 2500,
        },
        4: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 6,
            body: 8,
            mind: 6,
            exp: 2500,
        },
        5: {
            name: "Warrior",
            startingClass: "Fighter",
            skill: 4,
            body: 11,
            mind: 5,
            exp: 2000,
        },
        6: {
            name: "Warrior",
            startingClass: "Fighter",
            skill: 4,
            body: 11,
            mind: 5,
            exp: 2000,
        },
        7: {
            name: "Brawler",
            startingClass: "Grappler",
            skill: 5,
            body: 10,
            mind: 5,
            exp: 2000,
        },
        8: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 4,
            body: 7,
            mind: 9,
            exp: 2000,
        },
        9: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 4,
            body: 7,
            mind: 9,
            exp: 2000,
        },
        10: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 6,
            body: 7,
            mind: 7,
            exp: 2000,
        },
        11: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 6,
            body: 7,
            mind: 7,
            exp: 2000,
        },
        12: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 6,
            body: 7,
            mind: 7,
            exp: 2000,
        },
    };
    SwordWorld.BackgroundUpdatedDwarf = {
        name: "Updated Dwarf Backgrounds",
        2: {
            name: "Bodybuilder",
            startingClass: "Enhancer",
            skill: 5,
            body: 9,
            mind: 6,
            exp: 2500,
        },
        3: {
            name: "Bodybuilder",
            startingClass: "Enhancer",
            skill: 5,
            body: 9,
            mind: 6,
            exp: 2500,
        },
        4: {
            name: "Bodybuilder",
            startingClass: "Enhancer",
            skill: 5,
            body: 9,
            mind: 6,
            exp: 2500,
        },
        5: {
            name: "Minstrel",
            startingClass: "Bard",
            skill: 4,
            body: 8,
            mind: 8,
            exp: 2500,
        },
        6: {
            name: "Minstrel",
            startingClass: "Bard",
            skill: 4,
            body: 8,
            mind: 8,
            exp: 2500,
        },
        7: {
            name: "Brawler",
            startingClass: "Fighter",
            skill: 3,
            body: 12,
            mind: 5,
            exp: 2000,
        },
        8: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 5,
            body: 6,
            mind: 9,
            exp: 2000,
        },
        9: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 5,
            body: 6,
            mind: 9,
            exp: 2000,
        },
        10: {
            name: "Agile Warrior",
            startingClass: "Fencer & Scout",
            skill: 7,
            body: 8,
            mind: 5,
            exp: 2000,
        },
        11: {
            name: "Agile Warrior",
            startingClass: "Fencer & Scout",
            skill: 7,
            body: 8,
            mind: 5,
            exp: 2000,
        },
        12: {
            name: "Agile Warrior",
            startingClass: "Fencer & Scout",
            skill: 7,
            body: 8,
            mind: 5,
            exp: 2000,
        },
    };
    SwordWorld.BackgroundTabbit = {
        name: "Tabbit Backgrounds",
        2: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 7,
            body: 5,
            mind: 10,
            exp: 2000,
        },
        3: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 7,
            body: 5,
            mind: 10,
            exp: 2000,
        },
        4: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 7,
            body: 5,
            mind: 10,
            exp: 2000,
        },
        5: {
            name: "Manipulator",
            startingClass: "Manipulator",
            skill: 6,
            body: 6,
            mind: 10,
            exp: 2000,
        },
        6: {
            name: "Manipulator",
            startingClass: "Manipulator",
            skill: 6,
            body: 6,
            mind: 10,
            exp: 2000,
        },
        7: {
            name: "Magician",
            startingClass: "Sorcerer",
            skill: 5,
            body: 7,
            mind: 10,
            exp: 2000,
        },
        8: {
            name: "Scholar",
            startingClass: "Sage",
            skill: 5,
            body: 8,
            mind: 9,
            exp: 2500,
        },
        9: {
            name: "Scholar",
            startingClass: "Sage",
            skill: 5,
            body: 8,
            mind: 9,
            exp: 2500,
        },
        10: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 8,
            body: 5,
            mind: 9,
            exp: 2000,
        },
        11: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 8,
            body: 5,
            mind: 9,
            exp: 2000,
        },
        12: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 8,
            body: 5,
            mind: 9,
            exp: 2000,
        },
    };
    SwordWorld.BackgroundUpdatedTabbit = {
        name: "Updated Tabbit Backgrounds",
        2: {
            name: "Minstrel",
            startingClass: "Bard",
            skill: 7,
            body: 7,
            mind: 8,
            exp: 2500,
        },
        3: {
            name: "Minstrel",
            startingClass: "Bard",
            skill: 7,
            body: 7,
            mind: 8,
            exp: 2500,
        },
        4: {
            name: "Minstrel",
            startingClass: "Bard",
            skill: 7,
            body: 7,
            mind: 8,
            exp: 2500,
        },
        5: {
            name: "Herbalist",
            startingClass: "Ranger",
            skill: 8,
            body: 6,
            mind: 8,
            exp: 2500,
        },
        6: {
            name: "Herbalist",
            startingClass: "Ranger",
            skill: 8,
            body: 6,
            mind: 8,
            exp: 2500,
        },
        7: {
            name: "Magician",
            startingClass: "Sorcerer",
            skill: 6,
            body: 5,
            mind: 11,
            exp: 2000,
        },
        8: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 4,
            body: 7,
            mind: 11,
            exp: 2500,
        },
        9: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 4,
            body: 7,
            mind: 11,
            exp: 2500,
        },
        10: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 8,
            body: 5,
            mind: 9,
            exp: 2500,
        },
        11: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 8,
            body: 5,
            mind: 9,
            exp: 2500,
        },
        12: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 8,
            body: 5,
            mind: 9,
            exp: 2500,
        },
    };
    SwordWorld.BackgroundRunefolk = {
        name: "Runefolk Backgrounds",
        2: {
            name: "Scholar",
            startingClass: "Sage",
            skill: 8,
            body: 10,
            mind: 8,
            exp: 2500,
        },
        3: {
            name: "Scholar",
            startingClass: "Sage",
            skill: 8,
            body: 10,
            mind: 8,
            exp: 2500,
        },
        4: {
            name: "Scholar",
            startingClass: "Sage",
            skill: 8,
            body: 10,
            mind: 8,
            exp: 2500,
        },
        5: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 12,
            body: 8,
            mind: 6,
            exp: 2000,
        },
        6: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 12,
            body: 8,
            mind: 6,
            exp: 2000,
        },
        7: {
            name: "Warrior",
            startingClass: "Fighter or Grappler",
            skill: 9,
            body: 12,
            mind: 5,
            exp: 2000,
        },
        8: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 12,
            body: 8,
            mind: 6,
            exp: 2000,
        },
        9: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 12,
            body: 8,
            mind: 6,
            exp: 2000,
        },
        10: {
            name: "Wizard",
            startingClass: "Sorcerer",
            skill: 9,
            body: 9,
            mind: 9,
            exp: 2000,
        },
        11: {
            name: "Wizard",
            startingClass: "Sorcerer",
            skill: 9,
            body: 9,
            mind: 9,
            exp: 2000,
        },
        12: {
            name: "Wizard",
            startingClass: "Sorcerer",
            skill: 9,
            body: 9,
            mind: 9,
            exp: 2000,
        },
    };
    SwordWorld.BackgroundUpdatedRunefolk = {
        name: "Updated Runefolk Backgrounds",
        2: {
            name: "Hobbyist",
            startingClass: "Sage or Bard",
            skill: 8,
            body: 8,
            mind: 10,
            exp: 2500,
        },
        3: {
            name: "Hobbyist",
            startingClass: "Sage or Bard",
            skill: 8,
            body: 8,
            mind: 10,
            exp: 2500,
        },
        4: {
            name: "Hobbyist",
            startingClass: "Sage or Bard",
            skill: 8,
            body: 8,
            mind: 10,
            exp: 2500,
        },
        5: {
            name: "Bodybuilder",
            startingClass: "Enhancer",
            skill: 10,
            body: 10,
            mind: 6,
            exp: 2500,
        },
        6: {
            name: "Bodybuilder",
            startingClass: "Enhancer",
            skill: 10,
            body: 10,
            mind: 6,
            exp: 2500,
        },
        7: {
            name: "Soldier",
            startingClass: "Fighter or Grappler",
            skill: 7,
            body: 11,
            mind: 8,
            exp: 2000,
        },
        8: {
            name: "Agile Warrior",
            startingClass: "Fencer & Scout",
            skill: 11,
            body: 9,
            mind: 6,
            exp: 2000,
        },
        9: {
            name: "Agile Warrior",
            startingClass: "Fencer & Scout",
            skill: 11,
            body: 9,
            mind: 6,
            exp: 2000,
        },
        10: {
            name: "Manipulator",
            startingClass: "Conjurer",
            skill: 7,
            body: 9,
            mind: 10,
            exp: 2000,
        },
        11: {
            name: "Manipulator",
            startingClass: "Conjurer",
            skill: 7,
            body: 9,
            mind: 10,
            exp: 2000,
        },
        12: {
            name: "Manipulator",
            startingClass: "Conjurer",
            skill: 7,
            body: 9,
            mind: 10,
            exp: 2000,
        },
    };
    SwordWorld.BackgroundNightmare = {
        name: "Nightmare Backgrounds",
        2: {
            name: "Wizard",
            startingClass: "Sorcerer",
            skill: 5,
            body: 13,
            mind: 12,
            exp: 2000,
        },
        3: {
            name: "Wizard",
            startingClass: "Sorcerer",
            skill: 5,
            body: 13,
            mind: 12,
            exp: 2000,
        },
        4: {
            name: "Wizard",
            startingClass: "Sorcerer",
            skill: 5,
            body: 13,
            mind: 12,
            exp: 2000,
        },
        5: {
            name: "Warrior",
            startingClass: "Fighter or Grappler",
            skill: 7,
            body: 15,
            mind: 8,
            exp: 2000,
        },
        6: {
            name: "Warrior",
            startingClass: "Fighter or Grappler",
            skill: 7,
            body: 15,
            mind: 8,
            exp: 2000,
        },
        7: {
            name: "Agile Warrior",
            startingClass: "Fencer & Scout",
            skill: 11,
            body: 13,
            mind: 6,
            exp: 2000,
        },
        8: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 6,
            body: 14,
            mind: 10,
            exp: 2000,
        },
        9: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 6,
            body: 14,
            mind: 10,
            exp: 2000,
        },
        10: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 9,
            body: 9,
            mind: 12,
            exp: 2000,
        },
        11: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 9,
            body: 9,
            mind: 12,
            exp: 2000,
        },
        12: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 9,
            body: 9,
            mind: 12,
            exp: 2000,
        },
    };
    //Bookmark
    SwordWorld.BackgroundUpdatedNightmare = {
        name: "Updated Nightmare Backgrounds",
        2: {
            name: "Manipulator",
            startingClass: "Conjurer",
            skill: 5,
            body: 12,
            mind: 13,
            exp: 2000,
        },
        3: {
            name: "Manipulator",
            startingClass: "Conjurer",
            skill: 5,
            body: 12,
            mind: 13,
            exp: 2000,
        },
        4: {
            name: "Manipulator",
            startingClass: "Conjurer",
            skill: 5,
            body: 12,
            mind: 13,
            exp: 2000,
        },
        5: {
            name: "Hobbyist",
            startingClass: "Sage & Bard",
            skill: 10,
            body: 10,
            mind: 10,
            exp: 2000,
        },
        6: {
            name: "Hobbyist",
            startingClass: "Sage & Bard",
            skill: 10,
            body: 10,
            mind: 10,
            exp: 2000,
        },
        7: {
            name: "Soldier",
            startingClass: "Fighter or Grappler",
            skill: 8,
            body: 13,
            mind: 9,
            exp: 2000,
        },
        8: {
            name: "Magician",
            startingClass: "Sorcerer",
            skill: 7,
            body: 10,
            mind: 13,
            exp: 2000,
        },
        9: {
            name: "Magician",
            startingClass: "Sorcerer",
            skill: 7,
            body: 10,
            mind: 13,
            exp: 2000,
        },
        10: {
            name: "Agile Warrior",
            startingClass: "Fencer & Enhancer",
            skill: 12,
            body: 12,
            mind: 6,
            exp: 2000,
        },
        11: {
            name: "Agile Warrior",
            startingClass: "Fencer & Enhancer",
            skill: 12,
            body: 12,
            mind: 6,
            exp: 2000,
        },
        12: {
            name: "Agile Warrior",
            startingClass: "Fencer & Enhancer",
            skill: 12,
            body: 12,
            mind: 6,
            exp: 2000,
        },
    };
    SwordWorld.BackgroundShadow = {
        name: "Shadow Backgrounds",
        2: {
            name: "Hermit",
            startingClass: "Ranger",
            skill: 15,
            body: 6,
            mind: 6,
            exp: 2500,
        },
        3: {
            name: "Hermit",
            startingClass: "Ranger",
            skill: 15,
            body: 6,
            mind: 6,
            exp: 2500,
        },
        4: {
            name: "Hermit",
            startingClass: "Ranger",
            skill: 15,
            body: 6,
            mind: 6,
            exp: 2500,
        },
        5: {
            name: "Warrior",
            startingClass: "Fencer",
            skill: 17,
            body: 7,
            mind: 3,
            exp: 2500,
        },
        6: {
            name: "Warrior",
            startingClass: "Fencer",
            skill: 17,
            body: 7,
            mind: 3,
            exp: 2500,
        },
        7: {
            name: "Spy",
            startingClass: "Scout",
            skill: 16,
            body: 7,
            mind: 4,
            exp: 2500,
        },
        8: {
            name: "Brawler",
            startingClass: "Grappler",
            skill: 14,
            body: 8,
            mind: 5,
            exp: 2000,
        },
        9: {
            name: "Brawler",
            startingClass: "Grappler",
            skill: 14,
            body: 8,
            mind: 5,
            exp: 2000,
        },
        10: {
            name: "Soldier",
            startingClass: "Fighter",
            skill: 16,
            body: 9,
            mind: 3,
            exp: 2000,
        },
        11: {
            name: "Soldier",
            startingClass: "Fighter",
            skill: 16,
            body: 9,
            mind: 3,
            exp: 2000,
        },
        12: {
            name: "Soldier",
            startingClass: "Fighter",
            skill: 16,
            body: 9,
            mind: 3,
            exp: 2000,
        },
    };
    SwordWorld.BackgroundUpdatedShadow = {
        name: "Updated Shadow Backgrounds",
        2: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 17,
            body: 5,
            mind: 5,
            exp: 2000,
        },
        3: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 17,
            body: 5,
            mind: 5,
            exp: 2000,
        },
        4: {
            name: "Magitech",
            startingClass: "Artificer",
            skill: 17,
            body: 5,
            mind: 5,
            exp: 2000,
        },
        5: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 18,
            body: 6,
            mind: 3,
            exp: 2500,
        },
        6: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 18,
            body: 6,
            mind: 3,
            exp: 2500,
        },
        7: {
            name: "Bodybuilder",
            startingClass: "Enhancer",
            skill: 16,
            body: 6,
            mind: 5,
            exp: 2500,
        },
        8: {
            name: "Hobbyist",
            startingClass: "Sage & Bard",
            skill: 14,
            body: 8,
            mind: 5,
            exp: 2000,
        },
        9: {
            name: "Hobbyist",
            startingClass: "Sage & Bard",
            skill: 14,
            body: 8,
            mind: 5,
            exp: 2000,
        },
        10: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 13,
            body: 7,
            mind: 7,
            exp: 2000,
        },
        11: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 13,
            body: 7,
            mind: 7,
            exp: 2000,
        },
        12: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 13,
            body: 7,
            mind: 7,
            exp: 2000,
        },
    };
    SwordWorld.BackgroundLildraken = {
        name: "Lildraken Backgrounds",
        2: {
            name: "Hunter",
            startingClass: "Ranger",
            skill: 6,
            body: 11,
            mind: 8,
            exp: 2500,
        },
        3: {
            name: "Hunter",
            startingClass: "Ranger",
            skill: 6,
            body: 11,
            mind: 8,
            exp: 2500,
        },
        4: {
            name: "Brawler",
            startingClass: "Grappler",
            skill: 6,
            body: 13,
            mind: 6,
            exp: 2000,
        },
        5: {
            name: "Brawler",
            startingClass: "Grappler",
            skill: 6,
            body: 13,
            mind: 6,
            exp: 2000,
        },
        6: {
            name: "Warrior",
            startingClass: "Fighter",
            skill: 5,
            body: 14,
            mind: 6,
            exp: 2000,
        },
        7: {
            name: "Warrior",
            startingClass: "Fighter",
            skill: 5,
            body: 14,
            mind: 6,
            exp: 2000,
        },
        8: {
            name: "Warrior",
            startingClass: "Fighter",
            skill: 5,
            body: 14,
            mind: 6,
            exp: 2000,
        },
        9: {
            name: "Merchant",
            startingClass: "Sage",
            skill: 5,
            body: 11,
            mind: 9,
            exp: 2500,
        },
        10: {
            name: "Merchant",
            startingClass: "Sage",
            skill: 5,
            body: 11,
            mind: 9,
            exp: 2500,
        },
        11: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 7,
            body: 11,
            mind: 7,
            exp: 2500,
        },
        12: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 7,
            body: 11,
            mind: 7,
            exp: 2500,
        },
    };
    SwordWorld.BackgroundGrassrunner = {
        name: "Grassrunner Backgrounds",
        2: {
            name: "Warrior",
            startingClass: "Fencer",
            skill: 12,
            body: 5,
            mind: 9,
            exp: 2500,
        },
        3: {
            name: "Warrior",
            startingClass: "Fencer",
            skill: 12,
            body: 5,
            mind: 9,
            exp: 2500,
        },
        4: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 13,
            body: 5,
            mind: 8,
            exp: 2500,
        },
        5: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 13,
            body: 5,
            mind: 8,
            exp: 2500,
        },
        6: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 10,
            body: 4,
            mind: 12,
            exp: 2000,
        },
        7: {
            name: "Magician",
            startingClass: "Sorcerer",
            skill: 10,
            body: 3,
            mind: 13,
            exp: 2000,
        },
        8: {
            name: "Manipulator",
            startingClass: "Conjurer",
            skill: 9,
            body: 4,
            mind: 13,
            exp: 2000,
        },
        9: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 9,
            body: 5,
            mind: 12,
            exp: 2000,
        },
        10: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 9,
            body: 5,
            mind: 12,
            exp: 2000,
        },
        11: {
            name: "Herbalist",
            startingClass: "Sage & Ranger",
            skill: 10,
            body: 5,
            mind: 11,
            exp: 2000,
        },
        12: {
            name: "Herbalist",
            startingClass: "Sage & Ranger",
            skill: 10,
            body: 5,
            mind: 11,
            exp: 2000,
        },
    };
    SwordWorld.BackgroundNewman = {
        name: "Newman Backgrounds",
        2: {
            name: "Warrior",
            startingClass: "Fencer",
            skill: 12,
            body: 5,
            mind: 9,
            exp: 2500,
        },
        3: {
            name: "Warrior",
            startingClass: "Fencer",
            skill: 12,
            body: 5,
            mind: 9,
            exp: 2500,
        },
        4: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 13,
            body: 5,
            mind: 8,
            exp: 2500,
        },
        5: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 13,
            body: 5,
            mind: 8,
            exp: 2500,
        },
        6: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 10,
            body: 4,
            mind: 12,
            exp: 2000,
        },
        7: {
            name: "Magician",
            startingClass: "Sorcerer",
            skill: 10,
            body: 3,
            mind: 13,
            exp: 2000,
        },
        8: {
            name: "Manipulator",
            startingClass: "Conjurer",
            skill: 9,
            body: 4,
            mind: 13,
            exp: 2000,
        },
        9: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 9,
            body: 5,
            mind: 12,
            exp: 2000,
        },
        10: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 9,
            body: 5,
            mind: 12,
            exp: 2000,
        },
        11: {
            name: "Herbalist",
            startingClass: "Sage & Ranger",
            skill: 10,
            body: 5,
            mind: 11,
            exp: 2000,
        },
        12: {
            name: "Herbalist",
            startingClass: "Sage & Ranger",
            skill: 10,
            body: 5,
            mind: 11,
            exp: 2000,
        },
    };
    SwordWorld.BackgroundValkyrie = {
        name: "Valkyrie Backgrounds",
        2: {
            name: "Warrior",
            startingClass: "Fencer",
            skill: 12,
            body: 5,
            mind: 9,
            exp: 2500,
        },
        3: {
            name: "Warrior",
            startingClass: "Fencer",
            skill: 12,
            body: 5,
            mind: 9,
            exp: 2500,
        },
        4: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 13,
            body: 5,
            mind: 8,
            exp: 2500,
        },
        5: {
            name: "Archer",
            startingClass: "Marksman",
            skill: 13,
            body: 5,
            mind: 8,
            exp: 2500,
        },
        6: {
            name: "Feytouched",
            startingClass: "Fairy Tamer",
            skill: 10,
            body: 4,
            mind: 12,
            exp: 2000,
        },
        7: {
            name: "Magician",
            startingClass: "Sorcerer",
            skill: 10,
            body: 3,
            mind: 13,
            exp: 2000,
        },
        8: {
            name: "Manipulator",
            startingClass: "Conjurer",
            skill: 9,
            body: 4,
            mind: 13,
            exp: 2000,
        },
        9: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 9,
            body: 5,
            mind: 12,
            exp: 2000,
        },
        10: {
            name: "Cleric",
            startingClass: "Priest",
            skill: 9,
            body: 5,
            mind: 12,
            exp: 2000,
        },
        11: {
            name: "Herbalist",
            startingClass: "Sage & Ranger",
            skill: 10,
            body: 5,
            mind: 11,
            exp: 2000,
        },
        12: {
            name: "Herbalist",
            startingClass: "Sage & Ranger",
            skill: 10,
            body: 5,
            mind: 11,
            exp: 2000,
        },
    };
})(SwordWorld || (SwordWorld = {}));
//# sourceMappingURL=backgrounds.js.map