namespace kagegami {
    export let tableSpecial: Table = {
        11: traitAccOrdinary,
        12: traitAccWorrisome,
        13: traitAngel,
        14: traitAnimalFeature,
        15: traitAssistDevice,
        16: traitBodyFeature,
        21: traitCreepySmile,
        22: traitDemon,
        23: traitEyepatch,
        24: traitEyes,
        25: traitFace,
        26: traitTime,
        31: traitGhost,
        32: traitGlasses,
        33: traitAgent,
        34: traitHabit,
        35: traitHair,
        36: traitIncome,
        41: traitJewelry,
        42: traitKemonomimi,
        43: traitMachine,
        44: traitObsession,
        45: traitPersonality,
        46: traitPigtails,
        51: traitWolfs,
        52: traitSociety,
        53: traitSickly,
        54: traitSize,
        55: traitSkin,
        56: traitDiet,
        61: traitIdentity,
        62: traitSupernatural,
        63: traitTalent,
        64: traitTattoo,
        65: traitThirdEye,
        66: traitUnnatural
    };

    export let tableHobby: Table = {
        11: "Alchemy",
        12: "Anime",
        13: "Art",
        14: "Blogging",
        15: "Blood Rituals",
        16: "Chanting",
        21: "Coding",
        22: "Coffee",
        23: "Collecting",
        24: "Cooking",
        25: "Decoupage",
        26: "Divination",
        31: "Exorcism",
        32: "Fanfiction",
        33: "Fashion Design",
        34: "Flower Arrangement",
        35: "Gardening",
        36: "Going on Walks",
        41: "Gossip",
        42: "Inventing Stuff",
        43: "Jogging",
        44: "Knitting/Needlepoint",
        45: "Martian Arts",
        46: "Movies",
        51: "Phrenology",
        52: "Podcasting",
        53: "Poetry",
        54: "Reading",
        55: "Scrapbooking",
        56: "Sewing",
        61: "Soap Operas",
        62: "Spying",
        63: "Sudoku",
        64: "Tabletop Games",
        65: "Video Games",
        66: "Watching TV"
    };

    export let tableMotivation: Table = {
        11: "Accumulating Favors",
        12: "Achieving Greatness",
        13: "Adventure Calls to me",
        14: "Atonement",
        15: "Boredom",
        16: "Collecting Knowledge",
        21: "Creating a Better World",
        22: "Doing What's Right",
        23: "Empathy for Others",
        24: "Experiencing New Things",
        25: "Finding a Girlfriend",
        26: "Finding Pieces of the Puzzle",
        31: "Finding the Truth",
        32: "Following Friends",
        33: "Glory",
        34: "Having Fun",
        35: "Honor",
        36: "Just Plain a Good Person",
        41: "JUSTICE!",
        42: "Loneliness",
        43: "Making Friends",
        44: "Making my Parents proud",
        45: "Making others happy",
        46: "Need Money",
        51: "Proving I'm Better",
        52: "Proving my worth",
        53: "Reluctantly Doing the Right Thing",
        54: "Scientific Progress",
        55: "Secret Mission",
        56: "Seeking Approval",
        61: "Seeking Creative Inspiration",
        62: "Self-Improvement",
        63: "Showing Off",
        64: "Testing my Limits",
        65: "Want to Become Popular",
        66: "Want to Impress Someone"
    };

    export let tableExplosion: Table = {
        11: "Basking in Delusions",
        12: "Believing in Clouds",
        13: "Carving Strange Idols",
        14: "Cleaning",
        15: "Clutching a Plushie",
        16: "Cooking",
        21: "Creating Life",
        22: "Crying",
        23: "Cryptic Writings",
        24: "Doing Paperwork",
        25: "Drawing Manga",
        26: "Eating",
        31: "Eldritch Rituals",
        32: "Hiding in a Box",
        33: "Howling",
        34: "Improv Theater",
        35: "Informing on Friends",
        36: "Insulting the Moon",
        41: "Inventing Forbidden Technology",
        42: "Livetweeting",
        43: "Lying",
        44: "Partying",
        45: "Praying",
        46: "Reciting Coded Messages",
        51: "Recording Everything",
        52: "Singing",
        53: "Soul Escaping from the Body",
        54: "Splitting Apart",
        55: "Starting Fires",
        56: "Really Stealing? No Dignity.",
        61: "Studying",
        62: "Taking Notes",
        63: "Texting",
        64: "Violence",
        65: "Worshiping the Old Gods",
        66: "Writing Fanfiction"
    };

    export let tableColors: Table = {
        11: "Red",
        12: "Orange",
        13: "Yellow",
        14: "Green",
        15: "Blue",
        16: "Indigo",
        21: "Violet",
        22: "Black",
        23: "White",
        24: "Gray",
        25: "Brown",
        26: "Teal",
        31: "Maroon",
        32: "Magenta",
        33: "Gold",
        34: "Silver",
        35: "Copper",
        36: "Bronze",
        41: "Amber",
        42: "Turquoise",
        43: "Ice",
        44: "Rainbow",
        45: "Blood",
        46: "Tears",
        51: "Barcode",
        52: "Hound's Tooth",
        53: "Plaid",
        54: "Argyle",
        55: "Screentone",
        56: "Starlight",
        61: "Hypercolor",
        62: "Ultracolor",
        63: "Sparkly",
        64: "Prismatic",
        65: "Eldritch",
        66: "Varies"
    };

}